name: End-to-end tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv shell
          pipenv install --system
          playwright install chromium
      - name: Run tests
        run: pipenv run headless-default
      - name: Serve Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: reports
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history